// Generated by tools/gen_spec.py; do not edit.
package drmicro_pkg;
localparam integer ROM_MAINCPU_BASE=0, ROM_MAINCPU_SIZE=49152;
localparam integer ROM_GFX1_BASE=49152, ROM_GFX1_SIZE=16384;
localparam integer ROM_GFX2_BASE=65536, ROM_GFX2_SIZE=24576;
localparam integer ROM_ADPCM_BASE=90112, ROM_ADPCM_SIZE=16384;
localparam integer ROM_PROMS_BASE=106496, ROM_PROMS_SIZE=544;
localparam integer ROM_SIZE=107040;
localparam logic [7:0] DIP1_DEFAULT=8'h4d, DIP2_DEFAULT=8'h00;
endpackage
