"""Generate canonical ROM layout and DIP data from the pinned MAME driver."""
import json,pathlib,re,xml.etree.ElementTree as E
R=pathlib.Path(__file__).resolve().parents[1]
def main():
 src=(R/'reference/mame/src/mame/sanritsu/drmicro.cpp').read_text()
 regions=[]; cursor=0
 for m in re.finditer(r'ROM_REGION\(\s*(0x[\da-f]+),\s*"(\w+)"[^\n]*\n(.*?)(?=\s*ROM_REGION|ROM_END)',src,re.S):
  size,name,body=m.groups();parts=[];end=0
  for p in re.finditer(r'ROM_LOAD\(\s*"([^"]+)",\s*(0x[\da-f]+),\s*(0x[\da-f]+),\s*CRC\((\w+)\) SHA1\((\w+)\)',body):
   fn,off,n,crc,sha=p.groups();off=int(off,16);n=int(n,16)
   if off!=end:raise ValueError('Noncontiguous physical ROMs require explicit padding policy')
   parts.append(dict(name=fn,offset=off,length=n,crc32=crc,sha1=sha));end=off+n
  regions.append(dict(name=name,allocated=int(size,16),offset=cursor,length=end,parts=parts));cursor+=end
 dips=[];bank=-1;cur=None
 def label(s):
  m=re.search(r'DEF_STR\(\s*(\w+)\s*\)|"([^"]+)"',s)
  return (m[1] or m[2]).replace('_',' ')
 for line in src.splitlines():
  if 'PORT_START("DSW' in line:bank=int(re.search(r'DSW(\d)',line)[1])-1
  if bank<0:continue
  if 'INPUT_PORTS_END' in line:break
  m=re.search(r'PORT_DIPNAME\(\s*(0x\w+),\s*(0x\w+),\s*(.*?)\)\s*PORT_DIPLOCATION',line)
  if m:
   cur=dict(bank=bank,mask=int(m[1],16),default=int(m[2],16),name=label(m[3]),options=[]);dips.append(cur)
  m=re.search(r'PORT_DIPSETTING\(\s*(0x\w+),\s*(.*)',line)
  if m:cur['options'].append(dict(value=int(m[1],16),name=label(m[2])))
  m=re.search(r'PORT_(SERVICE|DIPUNUSED)_DIPLOC\(\s*(0x\w+)',line)
  if m:
   mask=int(m[2],16);dips.append(dict(bank=bank,mask=mask,default=0,name='Service Mode' if m[1]=='SERVICE' else f'Unused SW2:{mask.bit_length()}',options=[dict(value=0,name='Off'),dict(value=mask,name='On')]))
 defaults=[sum(d['default'] for d in dips if d['bank']==b) for b in range(2)]
 manifest=dict(set='drmicro',mame_commit=json.loads((R/'third_party.lock.json').read_text())['mame']['commit'],length=cursor,padding='none; populated bytes only',regions=regions,dips=dips,dip_defaults=defaults)
 (R/'reference/rom_manifest.json').write_text(json.dumps(manifest,indent=2)+'\n')
 (R/'rtl').mkdir(exist_ok=True)
 text='// Generated by tools/gen_spec.py; do not edit.\npackage drmicro_pkg;\n'
 for r in regions:
  text+=f"localparam integer ROM_{r['name'].upper()}_BASE={r['offset']}, ROM_{r['name'].upper()}_SIZE={r['length']};\n"
 text+=f"localparam integer ROM_SIZE={cursor};\nlocalparam logic [7:0] DIP1_DEFAULT=8'h{defaults[0]:02x}, DIP2_DEFAULT=8'h{defaults[1]:02x};\nendpackage\n"
 (R/'rtl/drmicro_pkg.sv').write_text(text)
 root=E.Element('misterromdescription')
 for k,v in [('name','Dr. Micro'),('setname','drmicro'),('rbf','Arcade-DrMicro'),('year','1983'),('manufacturer','Sanritsu'),('category','Platform'),('rotation','vertical'),('mameversion','0289'),('players','2'),('joystick','4-way'),('num_buttons','1')]:E.SubElement(root,k).text=v
 root.append(E.Comment('ROM metadata extracted from MAME '+manifest['mame_commit']+'; corroborated with MAME 0.289.'))
 sw=E.SubElement(root,'switches',{'default':','.join(f'{x:02x}' for x in defaults),'base':'0'})
 for d in dips:
  bits=[str(i+d['bank']*8) for i in range(8) if d['mask']>>i&1];opts=sorted(d['options'],key=lambda x:x['value'])
  E.SubElement(sw,'dip',{'name':d['name'],'bits':','.join(bits),'ids':','.join(o['name'] for o in opts)})
 E.SubElement(root,'buttons',{'names':'Action,Start 1,Start 2,Coin,Service','default':'A,Start,Select,R1,L1','count':'5'})
 rom=E.SubElement(root,'rom',{'index':'0','zip':'drmicro.zip'})
 for r in regions:
  for p in r['parts']:E.SubElement(rom,'part',{'name':p['name'],'crc':p['crc32']})
 (R/'releases').mkdir(exist_ok=True);E.indent(root);E.ElementTree(root).write(R/'releases/Dr. Micro.mra',encoding='utf-8',xml_declaration=True)
 print('Generated',cursor,'bytes; DIP defaults',defaults)
if __name__=='__main__':main()
